import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--surface-3) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        ink: {
          900: 'rgb(var(--ink-900) / <alpha-value>)',
          700: 'rgb(var(--ink-700) / <alpha-value>)',
          500: 'rgb(var(--ink-500) / <alpha-value>)',
          400: 'rgb(var(--ink-400) / <alpha-value>)',
        },
        brand: { 300: '#F2B5A3', 600: '#C2370F', 700: '#A12D0C' },
        focus: '#0F4FA8',
        success: '#1F7A3D',
        'success-soft': '#E4F2E8',
        warning: '#8A5A00',
        'warning-soft': '#FBF0DA',
        error: '#C42B1C',
        'error-soft': '#FBE6E3',
        info: '#1C5FBF',
        'info-soft': '#E4ECF8',
        // 15 Gen-I types — DEFAULT = badge (white text), tint = non-text accent
        type: {
          normal: { DEFAULT: '#6B6B5E', tint: '#EBEBE6' },
          fire: { DEFAULT: '#C2370F', tint: '#FAD9CF' },
          water: { DEFAULT: '#1C5FBF', tint: '#D6E2F5' },
          electric: { DEFAULT: '#806600', tint: '#F3E9C2' },
          grass: { DEFAULT: '#2E7D32', tint: '#D5EAD6' },
          ice: { DEFAULT: '#3E7C82', tint: '#D7EAEB' },
          fighting: { DEFAULT: '#B23222', tint: '#F4D4CF' },
          poison: { DEFAULT: '#7B3F99', tint: '#E7D6EF' },
          ground: { DEFAULT: '#9A6A1E', tint: '#EEE0C8' },
          flying: { DEFAULT: '#5C6FB1', tint: '#DBE0F0' },
          psychic: { DEFAULT: '#C2316E', tint: '#F7D3E0' },
          bug: { DEFAULT: '#5A7A1E', tint: '#DEE8C8' },
          rock: { DEFAULT: '#7A6A3E', tint: '#E7E1D2' },
          ghost: { DEFAULT: '#4E4376', tint: '#DAD5E6' },
          dragon: { DEFAULT: '#4A3FB5', tint: '#D9D6F0' },
        },
        confidence: {
          pokeapi: '#1F7A3D',
          curated: '#1C5FBF',
          inferred: '#8A5A00',
          unknown: '#5E6056',
        },
        // stat-bar magnitude tiers (NOT type colors)
        stat: { low: '#B23222', mid: '#8A5A00', high: '#1F7A3D', elite: '#1C5FBF' },
      },
      fontFamily: {
        display: ['"Silkscreen"', 'monospace'],
        sans: ['"Atkinson Hyperlegible"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.694rem', { lineHeight: '1.45' }],
        xs: ['0.833rem', { lineHeight: '1.45' }],
        sm: ['0.875rem', { lineHeight: '1.5' }],
        base: ['1rem', { lineHeight: '1.6' }],
        lg: ['1.125rem', { lineHeight: '1.55' }],
        xl: ['1.266rem', { lineHeight: '1.4' }],
        '2xl': ['1.602rem', { lineHeight: '1.3' }],
        '3xl': ['2.027rem', { lineHeight: '1.25' }],
        display: ['2.566rem', { lineHeight: '1.15' }],
      },
      borderRadius: { none: '0', sm: '4px', md: '8px', lg: '12px', full: '9999px' },
      borderWidth: { frame: '2px' },
      boxShadow: {
        sm: '0 1px 2px rgba(26,27,23,0.06)',
        md: '0 4px 12px rgba(26,27,23,0.10)',
        lg: '0 12px 32px rgba(26,27,23,0.16)',
        focus: '0 0 0 3px rgba(15,79,168,0.45)',
      },
      maxWidth: { sm: '640px', md: '768px', lg: '1024px', xl: '1200px', '2xl': '1320px' },
      transitionTimingFunction: { sheet: 'cubic-bezier(0.2,0.8,0.2,1)' },
    },
  },
  plugins: [],
} satisfies Config;
